# Site settings
title: Designer Fonctionnel
description: Je traduis vos idées en termes techniques pour les réaliser.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Designer Fonctionnel
user_description: Rédaction de documents fonctionnels dans le but de décrire ou documenter tout type de système informatique.  
user_title: Designer Fonctionnel
email: designerfonctionnel@gmail.com
twitter_username: iamhenri
github_username:  iamhenri
linkedin_username:  h3nr1

# Google-analytics
google-analytics:
  id: "364813381"

exclude: ['package.json', 'src' , 'node_modules']
