# Site settings
title: Designer Fonctionnel
description: Je traduis vos idées en termes techniques et fonctionnels.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Designer Fonctionnel
user_description: Rédaction de documents fonctionnels.  
user_title: Henri.L
email: designerfonctionnel@gmail.com
twitter_username: iamhenri
github_username:  iamhenri
linkedin_username:  h3nr1

# Google-analytics
google-analytics:
  id: "G-1SK9N18GL6"

exclude: ['package.json', 'src' , 'node_modules']
